services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Bytmig123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"

      ConnectionStrings__DefaultConnection: "Server=db;Database=EshopDb;User Id=sa;Password=Bytmig123!;TrustServerCertificate=True;Encrypt=False;"

      Stripe__SecretKey: "s"
      Stripe__PublishableKey: "m"
      Stripe__WebhookSecret: "w"

      PostNord__BaseUrl: "https://atapi2.postnord.com/rest/businesslocation"
      PostNord__ApiKey: "din-nyckel-här"

      Jwt__Issuer: "Pallshoppen"
      Jwt__Audience: "Pallshoppen.Client"
      Jwt__Key: "byt-ut-den-här-i-riktig-miljö"
    ports:
      - "8080:8080"

volumes:
  mssql_data:
